import os
"""
AEGIS Audit & Provenance System
==============================

Sistema avançado de auditoria e rastreamento de proveniência para código IA:
- Logs imutáveis com blockchain-like hashing
- Code watermarking para rastreamento
- Auditoria completa de geração de código
- Compliance e accountability

Otimizado para mobile (6GB RAM mínimo)
"""

import json
import hashlib
import time
import base64
import logging
import asyncio
import sqlite3
import os
from typing import Dict, List, Any, Optional, Tuple, Union
from dataclasses import dataclass, field, asdict
from enum import Enum
from datetime import datetime, timezone
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor

from quimera.logs.parser import montar_log


class AuditEventType(Enum):
    """Tipos de eventos de auditoria"""
    CODE_GENERATION = "code_generation"
    CODE_MODIFICATION = "code_modification"
    CODE_VALIDATION = "code_validation"
    SECURITY_SCAN = "security_scan"
    THREAT_DETECTION = "threat_detection"
    USER_INTERACTION = "user_interaction"
    SYSTEM_ACTION = "system_action"
    COMPLIANCE_CHECK = "compliance_check"


class ProvenienceLevel(Enum):
    """Níveis de rastreamento de proveniência"""
    BASIC = "basic"          # Hash e timestamp
    STANDARD = "standard"    # + Modelo usado, input/output
    DETAILED = "detailed"    # + Contexto completo, parâmetros
    FORENSIC = "forensic"    # + Watermark, chain completa


@dataclass
class AuditEvent:
    """Evento de auditoria individual"""
    event_id: str
    event_type: AuditEventType
    timestamp: datetime
    user_id: Optional[str]
    session_id: str
    component: str
    action: str
    details: Dict[str, Any]
    content_hash: str
    previous_hash: str = ""
    block_hash: str = ""
    chain_position: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Converte para dicionário"""
        return {
            'event_id': self.event_id,
            'event_type': self.event_type.value,
            'timestamp': self.timestamp.isoformat(),
            'user_id': self.user_id,
            'session_id': self.session_id,
            'component': self.component,
            'action': self.action,
            'details': self.details,
            'content_hash': self.content_hash,
            'previous_hash': self.previous_hash,
            'block_hash': self.block_hash,
            'chain_position': self.chain_position
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'AuditEvent':
        """Cria evento de dicionário"""
        return cls(
            event_id=data['event_id'],
            event_type=AuditEventType(data['event_type']),
            timestamp=datetime.fromisoformat(data['timestamp']),
            user_id=data.get('user_id'),
            session_id=data['session_id'],
            component=data['component'],
            action=data['action'],
            details=data['details'],
            content_hash=data['content_hash'],
            previous_hash=data.get('previous_hash', ''),
            block_hash=data.get('block_hash', ''),
            chain_position=data.get('chain_position', 0)
        )


@dataclass
class CodeProvenance:
    """Informações de proveniência de código"""
    code_id: str
    original_hash: str
    current_hash: str
    generation_timestamp: datetime
    model_used: str
    input_prompt: str
    generation_parameters: Dict[str, Any]
    validation_results: List[Dict[str, Any]]
    modifications: List[Dict[str, Any]]
    watermark: Optional[str] = None
    parent_code_ids: List[str] = field(default_factory=list)
    compliance_tags: List[str] = field(default_factory=list)


class CodeWatermarkEngine:
    """Motor de watermarking de código"""
    
    def __init__(self, secret_key: str):
        self.secret_key = secret_key
        
    def generate_watermark(self, code: str, metadata: Dict[str, Any]) -> str:
        """Gera watermark único para código"""
        # Combina código + metadata + timestamp + chave secreta
        timestamp = str(int(time.time()))
        combined = f"{code}|{json.dumps(metadata, sort_keys=True)}|{timestamp}|{self.secret_key}"
        
        # Gera hash SHA-256
        watermark_hash = hashlib.sha256(combined.encode()).hexdigest()
        
        # Encoda em base64 para facilitar inserção no código
        watermark = base64.b64encode(watermark_hash[:32].encode()).decode()
        
        return f"QUIMERA_WM_{watermark}"
    
    def embed_watermark(self, code: str, watermark: str, language: str = "python") -> str:
        """Embeda watermark no código"""
        if language.lower() == "python":
            # Insere como comentário no início
            watermark_comment = f"# Generated by Quimera AI - Watermark: {watermark}\n"
            return watermark_comment + code
        elif language.lower() in ["javascript", "typescript"]:
            watermark_comment = f"// Generated by Quimera AI - Watermark: {watermark}\n"
            return watermark_comment + code
        elif language.lower() in ["java", "c", "cpp", "csharp"]:
            watermark_comment = f"/* Generated by Quimera AI - Watermark: {watermark} */\n"
            return watermark_comment + code
        else:
            # Fallback: adiciona como string no final
            return code + f'\n"{watermark}"\n'
    
    def extract_watermark(self, code: str) -> Optional[str]:
        """Extrai watermark do código"""
        import re
        
        # Padrões de busca para diferentes linguagens
        patterns = [
            r'# Generated by Quimera AI - Watermark: (QUIMERA_WM_[A-Za-z0-9+/=]+)',
            r'// Generated by Quimera AI - Watermark: (QUIMERA_WM_[A-Za-z0-9+/=]+)',
            r'/\* Generated by Quimera AI - Watermark: (QUIMERA_WM_[A-Za-z0-9+/=]+) \*/',
            r'"(QUIMERA_WM_[A-Za-z0-9+/=]+)"'
        ]
        
        for pattern in patterns:
            match = re.search(pattern, code)
            if match:
                return match.group(1)
                
        return None
    
    def verify_watermark(self, code: str, expected_metadata: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
        """Verifica se watermark é válido"""
        watermark = self.extract_watermark(code)
        if not watermark:
            return False, "Watermark não encontrado"
        
        # Remove watermark do código para verificação
        clean_code = self._remove_watermark(code)
        
        # Tenta diferentes timestamps (tolerância de alguns segundos)
        current_time = int(time.time())
        for time_offset in range(-300, 301, 60):  # ±5 minutos
            test_timestamp = str(current_time + time_offset)
            combined = f"{clean_code}|{json.dumps(expected_metadata, sort_keys=True)}|{test_timestamp}|{self.secret_key}"
            test_hash = hashlib.sha256(combined.encode()).hexdigest()
            test_watermark = f"QUIMERA_WM_{base64.b64encode(test_hash[:32].encode()).decode()}"
            
            if test_watermark == watermark:
                return True, "Watermark válido"
        
        return False, "Watermark inválido ou corrompido"
    
    def _remove_watermark(self, code: str) -> str:
        """Remove watermark do código"""
        import re
        
        # Remove comentários de watermark
        patterns = [
            r'# Generated by Quimera AI - Watermark: QUIMERA_WM_[A-Za-z0-9+/=]+\n',
            r'// Generated by Quimera AI - Watermark: QUIMERA_WM_[A-Za-z0-9+/=]+\n',
            r'/\* Generated by Quimera AI - Watermark: QUIMERA_WM_[A-Za-z0-9+/=]+ \*/\n',
            r'"QUIMERA_WM_[A-Za-z0-9+/=]+"\n'
        ]
        
        clean_code = code
        for pattern in patterns:
            clean_code = re.sub(pattern, '', clean_code)
            
        return clean_code


class ImmutableAuditLog:
    """Log de auditoria imutável com estrutura blockchain-like"""
    
    def __init__(self, db_path: str):
        self.db_path = db_path
        self.chain_lock = asyncio.Lock()
        self._init_database()
        
    def _init_database(self):
        """Inicializa banco de dados SQLite"""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS audit_chain (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    event_id TEXT UNIQUE NOT NULL,
                    event_type TEXT NOT NULL,
                    timestamp TEXT NOT NULL,
                    user_id TEXT,
                    session_id TEXT NOT NULL,
                    component TEXT NOT NULL,
                    action TEXT NOT NULL,
                    details TEXT NOT NULL,
                    content_hash TEXT NOT NULL,
                    previous_hash TEXT NOT NULL,
                    block_hash TEXT NOT NULL,
                    chain_position INTEGER NOT NULL,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
                )
            """)
            
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_event_id ON audit_chain(event_id)
            """)
            
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_timestamp ON audit_chain(timestamp)
            """)
            
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_session ON audit_chain(session_id)
            """)
    
    async def add_event(self, event: AuditEvent) -> bool:
        """Adiciona evento ao log imutável"""
        async with self.chain_lock:
            try:
                # Calcula hash do evento anterior
                previous_hash = await self._get_last_block_hash()
                event.previous_hash = previous_hash
                
                # Calcula posição na chain
                event.chain_position = await self._get_next_position()
                
                # Calcula hash do bloco atual
                event.block_hash = self._calculate_block_hash(event)
                
                # Insere no banco
                with sqlite3.connect(self.db_path) as conn:
                    conn.execute("""
                        INSERT INTO audit_chain (
                            event_id, event_type, timestamp, user_id, session_id,
                            component, action, details, content_hash, previous_hash,
                            block_hash, chain_position
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, (
                        event.event_id, event.event_type.value, event.timestamp.isoformat(),
                        event.user_id, event.session_id, event.component, event.action,
                        json.dumps(event.details), event.content_hash, event.previous_hash,
                        event.block_hash, event.chain_position
                    ))
                
                return True
                
            except Exception as e:
                montar_log(f"❌ Erro ao adicionar evento ao log imutável: {e}", "ERROR")
                return False
    
    async def _get_last_block_hash(self) -> str:
        """Obtém hash do último bloco"""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT block_hash FROM audit_chain 
                ORDER BY chain_position DESC LIMIT 1
            """)
            result = cursor.fetchone()
            return result[0] if result else "genesis"
    
    async def _get_next_position(self) -> int:
        """Obtém próxima posição na chain"""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT MAX(chain_position) FROM audit_chain
            """)
            result = cursor.fetchone()
            return (result[0] + 1) if result and result[0] is not None else 0
    
    def _calculate_block_hash(self, event: AuditEvent) -> str:
        """Calcula hash do bloco"""
        block_data = f"{event.event_id}{event.timestamp.isoformat()}{event.content_hash}{event.previous_hash}{event.chain_position}"
        return hashlib.sha256(block_data.encode()).hexdigest()
    
    async def verify_chain_integrity(self) -> Tuple[bool, List[str]]:
        """Verifica integridade da chain"""
        issues = []
        
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT event_id, content_hash, previous_hash, block_hash, chain_position
                FROM audit_chain ORDER BY chain_position
            """)
            
            events = cursor.fetchall()
            
            if not events:
                return True, []
            
            # Verifica genesis block
            if events[0][2] != "genesis":  # previous_hash
                issues.append("Genesis block inválido")
            
            # Verifica chain
            for i in range(1, len(events)):
                current = events[i]
                previous = events[i-1]
                
                # Verifica se previous_hash aponta para o bloco anterior
                if current[2] != previous[3]:  # previous_hash != previous.block_hash
                    issues.append(f"Chain quebrada na posição {current[4]}")
                
                # Verifica posição sequencial
                if current[4] != previous[4] + 1:  # chain_position
                    issues.append(f"Posição não sequencial: {current[4]}")
        
        return len(issues) == 0, issues
    
    async def get_events_by_session(self, session_id: str) -> List[AuditEvent]:
        """Obtém eventos por sessão"""
        events = []
        
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute("""
                SELECT * FROM audit_chain WHERE session_id = ? ORDER BY chain_position
            """, (session_id,))
            
            for row in cursor.fetchall():
                event_data = {
                    'event_id': row[1],
                    'event_type': row[2],
                    'timestamp': row[3],
                    'user_id': row[4],
                    'session_id': row[5],
                    'component': row[6],
                    'action': row[7],
                    'details': json.loads(row[8]),
                    'content_hash': row[9],
                    'previous_hash': row[10],
                    'block_hash': row[11],
                    'chain_position': row[12]
                }
                events.append(AuditEvent.from_dict(event_data))
        
        return events
    
    async def search_events(self, filters: Dict[str, Any]) -> List[AuditEvent]:
        """Busca eventos por filtros"""
        where_clauses = []
        params = []
        
        if 'event_type' in filters:
            where_clauses.append("event_type = ?")
            params.append(filters['event_type'])
        
        if 'component' in filters:
            where_clauses.append("component = ?")
            params.append(filters['component'])
        
        if 'user_id' in filters:
            where_clauses.append("user_id = ?")
            params.append(filters['user_id'])
        
        if 'start_time' in filters:
            where_clauses.append("timestamp >= ?")
            params.append(filters['start_time'])
        
        if 'end_time' in filters:
            where_clauses.append("timestamp <= ?")
            params.append(filters['end_time'])
        
        where_sql = " AND ".join(where_clauses) if where_clauses else "1=1"
        
        events = []
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(f"""
                SELECT * FROM audit_chain WHERE {where_sql} ORDER BY chain_position
            """, params)
            
            for row in cursor.fetchall():
                event_data = {
                    'event_id': row[1],
                    'event_type': row[2],
                    'timestamp': row[3],
                    'user_id': row[4],
                    'session_id': row[5],
                    'component': row[6],
                    'action': row[7],
                    'details': json.loads(row[8]),
                    'content_hash': row[9],
                    'previous_hash': row[10],
                    'block_hash': row[11],
                    'chain_position': row[12]
                }
                events.append(AuditEvent.from_dict(event_data))
        
        return events


@dataclass
class AuditConfig:
    """Configuração do sistema de auditoria"""
    provenance_level: ProvenienceLevel = ProvenienceLevel.STANDARD
    enable_watermarking: bool = True
    enable_immutable_log: bool = True
    mobile_optimization: bool = True
    max_log_size_mb: int = 100  # Máximo para mobile
    retention_days: int = 90
    watermark_secret: str = os.getenv("QUIMERA_AEGIS_SECRET", "QUIMERA_AEGIS_2024_SECRET_KEY")


class AuditProvenanceSystem:
    """Sistema principal de auditoria e proveniência"""
    
    def __init__(self, config: Optional[AuditConfig] = None, db_path: Optional[str] = None):
        self.config = config or AuditConfig()
        
        # Inicializa componentes
        self.watermark_engine = CodeWatermarkEngine(self.config.watermark_secret)
        
        # Database path
        if db_path is None:
            db_path = "/tmp/quimera_audit.db" if self.config.mobile_optimization else "quimera_audit.db"
        
        self.audit_log = ImmutableAuditLog(db_path)
        
        # Armazenamento de proveniência em memória (mobile-friendly)
        self.provenance_store: Dict[str, CodeProvenance] = {}
        
        # Estatísticas
        self.stats = {
            'events_logged': 0,
            'codes_tracked': 0,
            'watermarks_generated': 0,
            'integrity_checks': 0
        }
        
        montar_log(f"🔍 Audit & Provenance System inicializado (nível: {self.config.provenance_level.value})", "INFO")
    
    async def log_code_generation(self, code: str, metadata: Dict[str, Any], 
                                session_id: str, user_id: Optional[str] = None) -> str:
        """Registra geração de código com auditoria completa"""
        
        # Gera ID único para o código
        code_id = hashlib.sha256(f"{code}{time.time()}".encode()).hexdigest()[:16]
        
        # Calcula hash do conteúdo
        content_hash = hashlib.sha256(code.encode()).hexdigest()
        
        # Gera watermark se habilitado
        watermark = None
        watermarked_code = code
        if self.config.enable_watermarking:
            watermark_metadata = {
                'code_id': code_id,
                'model': metadata.get('model', 'unknown'),
                'timestamp': datetime.now(timezone.utc).isoformat()
            }
            watermark = self.watermark_engine.generate_watermark(code, watermark_metadata)
            watermarked_code = self.watermark_engine.embed_watermark(
                code, watermark, metadata.get('language', 'python')
            )
            self.stats['watermarks_generated'] += 1
        
        # Cria registro de proveniência
        provenance = CodeProvenance(
            code_id=code_id,
            original_hash=content_hash,
            current_hash=hashlib.sha256(watermarked_code.encode()).hexdigest(),
            generation_timestamp=datetime.now(timezone.utc),
            model_used=metadata.get('model', 'unknown'),
            input_prompt=metadata.get('prompt', ''),
            generation_parameters=metadata.get('parameters', {}),
            validation_results=[],
            modifications=[],
            watermark=watermark,
            parent_code_ids=metadata.get('parent_codes', []),
            compliance_tags=metadata.get('compliance_tags', [])
        )
        
        self.provenance_store[code_id] = provenance
        self.stats['codes_tracked'] += 1
        
        # Log de auditoria
        if self.config.enable_immutable_log:
            audit_event = AuditEvent(
                event_id=f"codegen_{code_id}_{int(time.time())}",
                event_type=AuditEventType.CODE_GENERATION,
                timestamp=datetime.now(timezone.utc),
                user_id=user_id,
                session_id=session_id,
                component="code_generator",
                action="generate_code",
                details={
                    'code_id': code_id,
                    'model': metadata.get('model', 'unknown'),
                    'prompt_length': len(metadata.get('prompt', '')),
                    'code_length': len(code),
                    'language': metadata.get('language', 'python'),
                    'watermarked': watermark is not None,
                    'provenance_level': self.config.provenance_level.value
                },
                content_hash=content_hash
            )
            
            await self.audit_log.add_event(audit_event)
            self.stats['events_logged'] += 1
        
        montar_log(f"📝 Código {code_id} registrado com auditoria completa", "INFO")
        
        return code_id
    
    async def log_validation_result(self, code_id: str, validation_result: Dict[str, Any],
                                  session_id: str, user_id: Optional[str] = None):
        """Registra resultado de validação"""
        
        # Atualiza proveniência
        if code_id in self.provenance_store:
            self.provenance_store[code_id].validation_results.append({
                'timestamp': datetime.now(timezone.utc).isoformat(),
                'result': validation_result
            })
        
        # Log de auditoria
        if self.config.enable_immutable_log:
            audit_event = AuditEvent(
                event_id=f"validation_{code_id}_{int(time.time())}",
                event_type=AuditEventType.CODE_VALIDATION,
                timestamp=datetime.now(timezone.utc),
                user_id=user_id,
                session_id=session_id,
                component="validation_engine",
                action="validate_code",
                details={
                    'code_id': code_id,
                    'validation_result': validation_result.get('overall_result', 'unknown'),
                    'score': validation_result.get('overall_score', 0),
                    'phases_executed': validation_result.get('phases_executed', 0),
                    'critical_issues': len(validation_result.get('critical_issues', []))
                },
                content_hash=hashlib.sha256(json.dumps(validation_result, sort_keys=True).encode()).hexdigest()
            )
            
            await self.audit_log.add_event(audit_event)
            self.stats['events_logged'] += 1
    
    async def log_security_event(self, event_type: str, details: Dict[str, Any],
                               session_id: str, user_id: Optional[str] = None):
        """Registra evento de segurança"""
        
        if self.config.enable_immutable_log:
            audit_event = AuditEvent(
                event_id=f"security_{event_type}_{int(time.time())}",
                event_type=AuditEventType.THREAT_DETECTION,
                timestamp=datetime.now(timezone.utc),
                user_id=user_id,
                session_id=session_id,
                component="aegis_security",
                action=event_type,
                details=details,
                content_hash=hashlib.sha256(json.dumps(details, sort_keys=True).encode()).hexdigest()
            )
            
            await self.audit_log.add_event(audit_event)
            self.stats['events_logged'] += 1
    
    def get_code_provenance(self, code_id: str) -> Optional[CodeProvenance]:
        """Obtém informações de proveniência de código"""
        return self.provenance_store.get(code_id)
    
    def verify_code_integrity(self, code: str, code_id: str) -> Tuple[bool, str]:
        """Verifica integridade do código usando watermark"""
        
        if not self.config.enable_watermarking:
            return True, "Watermarking desabilitado"
        
        provenance = self.get_code_provenance(code_id)
        if not provenance:
            return False, "Proveniência não encontrada"
        
        # Verifica watermark
        expected_metadata = {
            'code_id': code_id,
            'model': provenance.model_used,
            'timestamp': provenance.generation_timestamp.isoformat()
        }
        
        is_valid, message = self.watermark_engine.verify_watermark(code, expected_metadata)
        
        if is_valid:
            self.stats['integrity_checks'] += 1
            
        return is_valid, message
    
    async def generate_audit_report(self, session_id: Optional[str] = None,
                                  start_time: Optional[datetime] = None,
                                  end_time: Optional[datetime] = None) -> Dict[str, Any]:
        """Gera relatório de auditoria"""
        
        # Filtros para busca
        filters = {}
        if session_id:
            filters['session_id'] = session_id
        if start_time:
            filters['start_time'] = start_time.isoformat()
        if end_time:
            filters['end_time'] = end_time.isoformat()
        
        # Busca eventos
        events = await self.audit_log.search_events(filters)
        
        # Agrupa por tipo
        events_by_type = {}
        for event in events:
            event_type = event.event_type.value
            if event_type not in events_by_type:
                events_by_type[event_type] = []
            events_by_type[event_type].append(event)
        
        # Verifica integridade da chain
        chain_valid, chain_issues = await self.audit_log.verify_chain_integrity()
        
        report = {
            'report_generated_at': datetime.now(timezone.utc).isoformat(),
            'session_id': session_id,
            'time_range': {
                'start': start_time.isoformat() if start_time else None,
                'end': end_time.isoformat() if end_time else None
            },
            'summary': {
                'total_events': len(events),
                'events_by_type': {k: len(v) for k, v in events_by_type.items()},
                'chain_integrity': chain_valid,
                'chain_issues': chain_issues
            },
            'events': [event.to_dict() for event in events[-100:]],  # Últimos 100 para mobile
            'provenance_summary': {
                'total_codes_tracked': len(self.provenance_store),
                'watermarks_in_use': sum(1 for p in self.provenance_store.values() if p.watermark)
            },
            'statistics': self.stats.copy()
        }
        
        return report
    
    async def cleanup_old_data(self):
        """Limpa dados antigos para otimização mobile"""
        
        if not self.config.mobile_optimization:
            return
        
        cutoff_date = datetime.now(timezone.utc) - timedelta(days=self.config.retention_days)
        
        # Remove proveniências antigas da memória
        old_codes = [
            code_id for code_id, prov in self.provenance_store.items()
            if prov.generation_timestamp < cutoff_date
        ]
        
        for code_id in old_codes:
            del self.provenance_store[code_id]
        
        if old_codes:
            montar_log(f"🧹 Limpeza: removidos {len(old_codes)} registros de proveniência antigos", "INFO")
    
    def get_system_status(self) -> Dict[str, Any]:
        """Retorna status do sistema de auditoria"""
        return {
            'config': {
                'provenance_level': self.config.provenance_level.value,
                'watermarking_enabled': self.config.enable_watermarking,
                'immutable_log_enabled': self.config.enable_immutable_log,
                'mobile_optimized': self.config.mobile_optimization,
                'retention_days': self.config.retention_days
            },
            'statistics': self.stats.copy(),
            'storage': {
                'provenance_records': len(self.provenance_store),
                'estimated_memory_mb': len(self.provenance_store) * 0.1  # Estimativa rough
            }
        }