"""
Engineering Assistant — TheAnd's "Jarvis"

The conversational layer that translates free-form user messages into
structured missions and executes them through the existing Quimera modules.

CRITICAL DESIGN RULE:
    The LLM does NOT write code. It does NOT choose patches.
    It does NOT validate results. It does NOT reason about fixes.

    The LLM's ONLY job:
        1. Understand what the user wants
        2. Build a structured Mission object
        3. Hand it to the Planner → Orchestrator → Pipeline

    All engineering work is done by the existing modules:
    Planner, Orchestrator, Detection Engine, KnowledgeBroker,
    ASTPatcher, CandidateRanker, UnifiedMemory, BuildIntegration,
    Sandbox, PatchMemory, AEGIS.

Flow:
    User (free-form PT/EN/ES)
        ↓
    EngineeringAssistant.understand()
        ↓
    Mission (structured object)
        ↓
    Planner.plan() → decomposes into steps
        ↓
    Orchestrator.interpret_and_run() → full pipeline
        ↓
    EngineeringAssistant.explain() → conversational response
        ↓
    User gets a clear, evidence-backed answer
"""

import json
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("quimera.assistant")


# ═══════════════════════════════════════════════════════════════════════
# Domain model
# ═══════════════════════════════════════════════════════════════════════

class MissionKind(str, Enum):
    """What the user wants."""
    BUILD = "build"
    FIX = "fix"
    ANALYZE = "analyze"
    AUDIT = "audit"
    BENCHMARK = "benchmark"
    OPTIMIZE = "optimize"
    MIGRATE = "migrate"
    EXPLAIN = "explain"
    TEST = "test"
    SANITIZE = "sanitize"
    UPDATE = "update"
    HELP = "help"
    UNKNOWN = "unknown"


@dataclass
class Mission:
    """
    Structured contract between the assistant and Quimera modules.

    This is NOT a parser output. It is a formal specification of
    what the system should do, generated by the assistant from
    natural language.
    """
    kind: MissionKind = MissionKind.UNKNOWN
    description: str = ""                     # human-readable summary
    goal: str = ""                            # what to achieve
    project_path: str = "."                   # where the project lives
    project_type: str = ""                    # kernel, cmake, make, cargo...
    language: str = ""                        # c, cpp, rust, python...
    actions: List[str] = field(default_factory=list)
    error_context: str = ""                   # error message or symptom
    constraints: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.0                   # 0.0-1.0

    # constraints examples:
    #   {"sandbox": true, "free_models": true, "max_iterations": 20}
    #   {"compiler": "gcc", "arch": "arm64"}
    #   {"sanitizers": ["kasan", "ubsan"]}

    def to_dict(self) -> Dict:
        return {
            "kind": self.kind.value,
            "description": self.description,
            "goal": self.goal,
            "project_path": self.project_path,
            "project_type": self.project_type,
            "language": self.language,
            "actions": self.actions,
            "error_context": self.error_context,
            "constraints": self.constraints,
            "confidence": self.confidence,
        }


# ═══════════════════════════════════════════════════════════════════════
# Assistant
# ═══════════════════════════════════════════════════════════════════════

class EngineeringAssistant:
    """
    Conversational engineering assistant for Quimera.

    Usage:
        assistant = EngineeringAssistant(project_root=".")
        reply = await assistant.ask("Meu kernel entrou em bootloop")
        print(reply.message)

    The assistant:
      - Understands natural language (PT, EN, ES)
      - Creates structured Missions
      - Delegates to existing Quimera modules
      - Returns conversational responses with evidence
    """

    # ── System prompt for LLM-based interpretation ─────────────
    SYSTEM_PROMPT = """You are the Engineering Assistant for TheAnd, an autonomous software engineering platform.

Your ONLY job: translate natural language into a structured mission specification.

Return ONLY a JSON object. No explanations, no code, no markdown.

The JSON must have these fields:
{
  "kind": "build" | "fix" | "analyze" | "audit" | "benchmark" | "optimize" |
          "migrate" | "explain" | "test" | "sanitize" | "update" | "help" | "unknown",
  "description": "short summary of what the user wants",
  "goal": "what needs to be achieved",
  "project_type": "kernel" | "cmake" | "make" | "cargo" | "meson" | "bazel" | "generic" | "",
  "language": "c" | "cpp" | "rust" | "python" | "",
  "actions": ["step1", "step2", ...],
  "error_context": "error message or symptom if user mentions a problem, otherwise empty",
  "constraints": {
    "sandbox": true/false,
    "free_models": true/false,
    "max_iterations": number,
    "compiler": "gcc" | "clang" | "",
    "arch": "x86_64" | "arm64" | "riscv" | "",
    "sanitizers": ["kasan", "ubsan", "asan"]
  },
  "confidence": 0.0-1.0
}

RULES:
- kind="build" if user wants to compile/build/make something.
- kind="fix" if user mentions bugs, errors, crashes, segfaults, bootloops, panics, "corrigir", "consertar", "arrumar", "use-after-free", "buffer overflow", "null pointer".
- kind="audit" if user wants security analysis, vulnerability scan, CVE check.
- kind="analyze" if user wants code analysis without fixing.
- kind="benchmark" if user wants performance measurement.
- kind="optimize" if user wants speed/memory improvement.
- kind="migrate" if user wants to port/convert/rewrite to another language.
- kind="explain" if user wants to understand architecture or code.
- kind="test" if user wants to run or generate tests.
- kind="sanitize" if user wants to enable KASAN/UBSAN/ASAN.
- kind="update" if user wants to update dependencies or kernel version.
- kind="help" if user is asking what the system can do.

Extract error_context: the actual error message, symptom, or bug description.
Extract constraints: sandbox=true if user mentions security/isolation,
  free_models=true if user mentions "gratuito" or "free tier",
  max_iterations=20 for long-running tasks.

Confidence: 0.9+ if intent is crystal clear, 0.5-0.7 if ambiguous.
"""

    def __init__(self, project_root: str = ".", use_llm: bool = False):
        self.project_root = project_root
        self.use_llm = use_llm
        self._conversation_history: List[Dict] = []
        self._planner = None
        self._orchestrator = None
        self._interpreter = None

    # ── Public API ────────────────────────────────────────────

    async def ask(self, user_message: str) -> "AssistantReply":
        """
        Main entry point. User speaks → assistant understands → acts → replies.

        Returns an AssistantReply with conversational response and evidence.
        """
        self._conversation_history.append({"role": "user", "content": user_message})

        # Step 1: Understand
        mission = self._understand(user_message)

        # Step 2: Plan
        steps = self._plan(mission)

        # Step 3: Execute
        result = self._execute(mission)

        # Step 4: Explain
        reply = self._explain(mission, result)

        self._conversation_history.append({"role": "assistant", "content": reply.message})
        return reply

    def ask_sync(self, user_message: str) -> "AssistantReply":
        """Synchronous version for environments without asyncio."""
        import asyncio
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                # We're inside an event loop — create a new one
                import concurrent.futures
                with concurrent.futures.ThreadPoolExecutor() as executor:
                    future = executor.submit(asyncio.run, self.ask(user_message))
                    return future.result()
            return loop.run_until_complete(self.ask(user_message))
        except RuntimeError:
            return asyncio.run(self.ask(user_message))

    # ── Step 1: Understand ────────────────────────────────────

    def _understand(self, message: str) -> Mission:
        """Translate natural language → structured Mission."""
        msg_lower = message.lower()

        # Try LLM first if enabled
        if self.use_llm:
            llm_mission = self._understand_llm(message)
            if llm_mission and llm_mission.confidence > 0.6:
                return llm_mission

        # Fallback: keyword-based understanding (works without LLM)
        return self._understand_keywords(msg_lower, message)

    def _understand_keywords(self, msg: str, original: str) -> Mission:
        """Keyword-based mission extraction. Solid fallback when LLM unavailable."""

        # ── Determine kind ────────────────────────────────────
        kind = MissionKind.UNKNOWN
        scores: Dict[MissionKind, int] = {}

        patterns = {
            MissionKind.FIX: [
                "corrig", "consert", "arrum", "fix", "repair", "resolv",
                "erro", "error", "bug", "falha", "quebr", "crash",
                "segfault", "seg fault", "bootloop", "panic", "panico",
                "travou", "travando", "parou de funcionar", "não compila",
                "use-after-free", "use after free", "uaf",
                "buffer overflow", "buffer overrun", "estouro",
                "null pointer", "null deref", "ponteiro nulo",
                "memory leak", "vazamento", "double free",
                "race condition", "condição de corrida",
                "deadlock", "corrupção",
            ],
            MissionKind.BUILD: [
                "compil", "build", "make", "compila", "builda",
                "compilar", "buildar", "fazer build",
            ],
            MissionKind.AUDIT: [
                "audit", "auditar", "segurança", "security",
                "vulnerab", "cve", "pentest", "exploit",
                "encontre vulnerab", "scan de segurança",
            ],
            MissionKind.ANALYZE: [
                "analis", "analyz", "analisa", "analise",
                "descubra por que", "descobre por que",
                "entenda", "investigue",
            ],
            MissionKind.BENCHMARK: [
                "benchmark", "bench", "medir desempenho",
                "velocidade", "tempo de execução", "throughput",
            ],
            MissionKind.OPTIMIZE: [
                "otimiz", "optimiz", "lento", "devagar",
                "acelerar", "melhorar performance", "reduzir uso",
            ],
            MissionKind.MIGRATE: [
                "migra", "migrar", "portar", "porta", "converter",
                "reescrever", "traduzir pra", "mudar pra",
                "porta esse", "porta para", "porta pra",
            ],
            MissionKind.EXPLAIN: [
                "explica", "explique", "como funciona",
                "arquitetura", "entender", "resumo", "overview",
            ],
            MissionKind.TEST: [
                "teste", "test", "testar", "rodar teste",
                "executar teste", "pytest", "coverage",
            ],
            MissionKind.SANITIZE: [
                "kasan", "ubsan", "asan", "sanitizer",
                "ativar kasan", "enable kasan", "ligar kasan",
            ],
            MissionKind.UPDATE: [
                "atualiz", "update", "upgrade", "portar para kernel",
                "atualizar dependência", "versão nova",
            ],
            MissionKind.SANITIZE: [
                "kasan", "ubsan", "asan", "sanitizer",
                "ativar kasan", "enable kasan", "ligar kasan",
            ],
            MissionKind.HELP: [
                "o que você faz", "o que voce faz", "o que tu faz",
                "como usar", "help", "ajuda", "comandos",
                "o que pode fazer", "capacidades",
                "como funciona", "como usar voce", "como te usar",
            ],
        }

        for k, keywords in patterns.items():
            score = sum(1 for kw in keywords if kw in msg)
            if score > 0:
                scores[k] = score

        if scores:
            # Priority rules for multi-intent messages:
            # FIX > BUILD > AUDIT > ANALYZE > MIGRATE > SANITIZE > BENCHMARK > ...
            priority_order = [
                MissionKind.FIX, MissionKind.BUILD, MissionKind.AUDIT,
                MissionKind.ANALYZE, MissionKind.MIGRATE, MissionKind.TEST,
                MissionKind.OPTIMIZE, MissionKind.BENCHMARK,
                MissionKind.SANITIZE, MissionKind.UPDATE,
                MissionKind.EXPLAIN, MissionKind.HELP,
            ]
            for k in priority_order:
                if k in scores:
                    kind = k
                    break
            else:
                kind = max(scores, key=scores.get)
        elif "analise" in msg or "analisa" in msg:
            kind = MissionKind.ANALYZE

        # ── Extract error context ──────────────────────────────
        error_context = ""
        error_patterns = [
            (r'(?:erro|error|bug|falha|problema)[:\s]*["\']?([^"\'\n]{5,80})', 1),
            (r'(?:segfault|panic|panico|bootloop|crash)[:\s]*["\']?([^"\'\n]{5,80})', 1),
            (r'(?:use-after-free|uaf|buffer overflow|null pointer)[:\s]*["\']?([^"\'\n]{5,80})', 1),
        ]
        import re
        for pattern, group in error_patterns:
            m = re.search(pattern, original, re.IGNORECASE)
            if m:
                error_context = m.group(group).strip()
                break

        # ── Extract constraints ────────────────────────────────
        constraints = {
            "sandbox": False,
            "free_models": False,
            "max_iterations": 5,
            "compiler": "",
            "arch": "",
            "sanitizers": [],
        }

        if any(w in msg for w in ["sandbox", "isolado", "seguro", "container"]):
            constraints["sandbox"] = True
        if any(w in msg for w in ["gratuito", "grátis", "free", "sem custo", "somente free"]):
            constraints["free_models"] = True
        if any(w in msg for w in ["até funcionar", "ate funcionar", "continuar", "várias vezes"]):
            constraints["max_iterations"] = 20

        if "kasan" in msg:
            constraints["sanitizers"].append("kasan")
        if "ubsan" in msg:
            constraints["sanitizers"].append("ubsan")
        if "asan" in msg and "kasan" not in msg:
            constraints["sanitizers"].append("asan")

        if "gcc" in msg:
            constraints["compiler"] = "gcc"
        elif "clang" in msg:
            constraints["compiler"] = "clang"

        if "arm64" in msg or "aarch64" in msg:
            constraints["arch"] = "arm64"
        elif "riscv" in msg:
            constraints["arch"] = "riscv"
        elif "x86" in msg:
            constraints["arch"] = "x86_64"

        # ── Detect project type ────────────────────────────────
        project_type = ""
        language = ""
        if any(w in msg for w in ["kernel", "linux", "kasan", "ubsan", "bzImage"]):
            project_type = "kernel"
            language = "c"
        elif any(w in msg for w in ["cmake", "CMakeLists"]):
            project_type = "cmake"
            language = "cpp"
        elif any(w in msg for w in ["cargo", "rust"]):
            project_type = "cargo"
            language = "rust"

        # ── Generate description and goal ──────────────────────
        descriptions = {
            MissionKind.FIX: f"Corrigir erro{'s' if 'erros' in msg else ''} no código",
            MissionKind.BUILD: "Compilar o projeto",
            MissionKind.AUDIT: "Auditar segurança do código",
            MissionKind.ANALYZE: "Analisar código-fonte",
            MissionKind.BENCHMARK: "Medir desempenho",
            MissionKind.OPTIMIZE: "Otimizar performance",
            MissionKind.MIGRATE: "Migrar para outra linguagem",
            MissionKind.EXPLAIN: "Explicar arquitetura",
            MissionKind.TEST: "Executar testes",
            MissionKind.SANITIZE: "Ativar sanitizers",
            MissionKind.UPDATE: "Atualizar dependências",
            MissionKind.HELP: "Mostrar ajuda",
        }

        return Mission(
            kind=kind,
            description=descriptions.get(kind, "Analisar solicitação"),
            goal=original.strip()[:200],
            project_path=self.project_root,
            project_type=project_type,
            language=language,
            actions=["detect", "research", "generate", "validate"]
            if kind == MissionKind.FIX else ["run"],
            error_context=error_context,
            constraints=constraints,
            confidence=0.85 if len(scores) > 0 and max(scores.values()) >= 2 else 0.5,
        )

    def _understand_llm(self, message: str) -> Optional[Mission]:
        """Use LLM for understanding. Returns None if LLM unavailable."""
        try:
            from quimera.llm_client_factory import LLMClientFactory
            factory = LLMClientFactory()
            client = factory.get_client(prefer_free=True)
            if not client:
                return None

            response = client.chat(
                system=self.SYSTEM_PROMPT,
                messages=[{"role": "user", "content": message}],
                temperature=0.1,
                max_tokens=500,
            )

            data = json.loads(response)
            return Mission(
                kind=MissionKind(data.get("kind", "unknown")),
                description=data.get("description", ""),
                goal=data.get("goal", ""),
                project_path=self.project_root,
                project_type=data.get("project_type", ""),
                language=data.get("language", ""),
                actions=data.get("actions", []),
                error_context=data.get("error_context", ""),
                constraints=data.get("constraints", {}),
                confidence=float(data.get("confidence", 0.5)),
            )
        except Exception as e:
            logger.warning(f"LLM understanding failed: {e}")
            return None

    # ── Step 2: Plan ──────────────────────────────────────────

    def _plan(self, mission: Mission) -> List[str]:
        """Decompose mission into executable steps via Planner."""
        try:
            from quimera.planner import Planner
            if not self._planner:
                self._planner = Planner(project_root=mission.project_path)

            plan = self._planner.plan(mission.description)
            return [s.description for s in plan.steps] if plan and plan.steps else []
        except Exception as e:
            logger.warning(f"Planning failed: {e}")
            return []

    # ── Step 3: Execute ───────────────────────────────────────

    def _execute(self, mission: Mission) -> Dict:
        """Execute the mission through Quimera modules."""
        result = {
            "success": False,
            "status": "not_executed",
            "findings": 0,
            "candidates": 0,
            "phases": 0,
            "score": 0.0,
            "issues": [],
            "message": "",
        }

        try:
            from quimera.orchestrator import QuimeraOrchestrator, OrchestratorConfig

            config = OrchestratorConfig(
                project_root=mission.project_path,
                mission=mission.description,
                use_llm=self.use_llm,
                max_iterations=mission.constraints.get("max_iterations", 5),
            )
            orch = QuimeraOrchestrator(config)
            result = orch.interpret_and_run(mission.goal)
            return result
        except Exception as e:
            result["message"] = str(e)
            return result

    # ── Step 4: Explain ───────────────────────────────────────

    def _explain(self, mission: Mission, result: Dict) -> "AssistantReply":
        """Build a conversational, evidence-backed response."""
        kind = mission.kind
        success = result.get("success", False)
        findings = result.get("issues_found", result.get("findings", 0))
        candidates = result.get("candidates_generated", 0)
        phases = result.get("phases_completed", 0)
        score = result.get("final_score", 0)
        issues = result.get("issues_found", [])
        if isinstance(issues, int):
            issues = []

        # ── Build natural language response ──────────────────
        messages = []

        # Opening
        if kind == MissionKind.HELP:
            return AssistantReply(
                success=True,
                kind=kind,
                message=self._help_message(),
                evidence={},
            )

        if kind == MissionKind.FIX:
            if success:
                messages.append("✅ **Consegui corrigir!**")
                messages.append(f"O pipeline executou {phases} fases de validação.")
                if candidates:
                    messages.append(f"Gerei {candidates} candidatos de patch.")
                if score:
                    messages.append(f"Score final de confiança: {score:.0%}")
            elif findings > 0:
                messages.append(f"🔍 **Analisei o código e encontrei {findings} possíveis problemas.**")
                if candidates > 0:
                    messages.append(f"Gerei {candidates} candidatos de correção, mas nenhum passou em todas as validações.")
                    messages.append("Isso significa que o problema pode ser mais complexo do que uma correção automática.")
                elif phases >= 7:
                    messages.append("Executei o pipeline completo mas não consegui gerar um patch validado.")
                else:
                    messages.append("Executei a detecção mas o pipeline não completou todas as fases.")
            elif phases > 0:
                messages.append(f"Executei {phases} fases do pipeline mas não encontrei problemas evidentes.")
                messages.append("Pode ser uma dependência externa, configuração, ou problema em runtime que não aparece no código fonte.")
            else:
                messages.append("Tentei executar o pipeline de correção mas encontrei um erro.")
                if result.get("message"):
                    messages.append(f"Erro: {result['message']}")

        elif kind == MissionKind.AUDIT:
            if findings > 0:
                messages.append(f"🛡️ **Auditoria concluída. {findings} vulnerabilidades potenciais encontradas.**")
            else:
                messages.append("🛡️ Auditoria concluída. Nenhuma vulnerabilidade óbvia detectada.")

        elif kind == MissionKind.ANALYZE:
            if findings > 0:
                messages.append(f"📊 **Análise concluída. {findings} pontos de atenção.**")
            else:
                messages.append("📊 Análise concluída. Código parece limpo nas verificações básicas.")

        elif kind == MissionKind.BUILD:
            messages.append("🔧 **Build analisado.**" if phases > 0 else "🔧 Pipeline de build iniciado.")

        elif kind == MissionKind.BENCHMARK:
            messages.append("⏱️ **Benchmark concluído.**" if phases > 0 else "⏱️ Pipeline de benchmark iniciado.")

        elif kind == MissionKind.EXPLAIN:
            messages.append("📖 Para explicar a arquitetura, eu preciso analisar os arquivos do projeto.")
            messages.append("Use `quimera explain <caminho>` para uma análise detalhada.")

        elif kind == MissionKind.MIGRATE:
            messages.append("🔄 Migração de linguagem requer análise profunda da base de código.")
            messages.append("🔄 Migração de linguagem requer análise profunda da base de código. Use `quimera migrate <caminho> --target <lang>` para iniciar o processo guiado.")

        elif kind == MissionKind.TEST:
            messages.append("🧪 Para rodar testes, use `quimera test <caminho>`.")

        else:
            if phases > 0:
                messages.append(f"✅ Pipeline executou {phases} fases.")
            else:
                messages.append(
                    "Entendi sua solicitação. Para executá-la completamente, "
                    "preciso de um diretório de projeto com código-fonte C/C++."
                )

        # Add issue details if any
        if issues and isinstance(issues, list):
            messages.append("\n**Problemas detectados:**")
            for iss in issues[:5]:
                if isinstance(iss, dict):
                    cwe = iss.get("cwe", "")
                    desc = iss.get("desc", str(iss))
                    messages.append(f"• {cwe}: {desc[:100]}")

        return AssistantReply(
            success=success or findings > 0,
            kind=kind,
            message="\n".join(messages),
            evidence={
                "phases_completed": phases,
                "findings": findings,
                "candidates": candidates,
                "score": score,
            },
        )

    def _help_message(self) -> str:
        return """# 🦾 Quimera — Assistente de Engenharia

Eu posso ajudar você com:

🔧 **Corrigir bugs** — "Meu kernel deu bootloop", "Tem um use-after-free no handler"
🛡️ **Auditar segurança** — "Quero auditar meu projeto", "Encontre vulnerabilidades"
📊 **Analisar código** — "Analise esse projeto inteiro", "Descubra por que o build falha"
⏱️ **Benchmark** — "Rode benchmark", "Mede o desempenho"
🧪 **Testar** — "Rode os testes", "Gere uma suíte de testes"
🔄 **Migrar** — "Porta esse driver pra kernel 6.12"

**Exemplos do que você pode dizer:**
- "Compile meu kernel com KASAN e corrija tudo até funcionar"
- "Encontre vulnerabilidades e corrija as que forem possíveis"
- "Use somente modelos gratuitos e faça sandbox antes"
- "Explique a arquitetura desse projeto"

**O que eu NÃO faço:**
- Não escrevo código do zero
- Não substituo revisão humana
- Não funciono com Python, JavaScript, ou outras linguagens (C/C++ apenas)

Pronto para começar? É só falar!"""


# ═══════════════════════════════════════════════════════════════════════
# Reply object
# ═══════════════════════════════════════════════════════════════════════

@dataclass
class AssistantReply:
    """Response from the Engineering Assistant to the user."""
    success: bool
    kind: MissionKind
    message: str                               # conversational response
    evidence: Dict[str, Any] = field(default_factory=dict)   # structured data
    mission: Optional[Mission] = None          # original mission reference
